server:
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?userUnicode=True?characterEncoding=UTF-8?allowMultiQueries=True
    username: root
    password:
  session:
    timeout: 216000
  mail:
    host: smtp.sinpor.top
    port: 465
    username: eigb903@sinpor.top
    password: sinpor123
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            required: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
