spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?userUnicode=True?characterEncoding=UTF-8?allowMultiQueries=True
    username: root
    password: 150181
  session:
    s
mybatis:
  mapper-locations: classpath:mappers/*.xml
