server:
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?userUnicode=True?characterEncoding=UTF-8?allowMultiQueries=True
    username: root
    password: 150181
  session:
    timeout: 216000
  mail:
    host: smtp-mail.outlook.com
    port: 589
    username: LuluDominic97@outlook.fr
    password: KQVWztgr0730
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            required: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
